services:
  app:
    build: .
    container_name: whale-app
    ports:
      - '3001:3001'
    depends_on:
      - redis
    env_file:
      - .env

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

volumes:
  redis_data:
